from redis.exception import RedisError


class ConnectionInvalidContext(RedisError):
    pass
